### ISSUE TITLE
How to install this plugin in kong 

### ISSUE THREAD

**Issue by chatchaisi** [matthyx/kong-elastic-apm#2]
Hi. 

   How to install this plugin. Do you have any document to install ? 

Thank you

**Comment by matthyx** [comment]
Hello @chatchaisi thanks for reaching out.
Let me add some stuff to the README in the next few days.
I will also make some commits to address the performance bottleneck of the go-pluginserver.

**Comment by matthyx** [comment]
Please check the docker-compose file for an example.

**Comment by chatchaisi** [comment]
Thank you.

**Comment by matthyx** [comment]
You're welcome. Let me know how it goes...
