### ISSUE TITLE
When will this be "intended for production use"

### ISSUE THREAD

**Issue by soer7022** [matthyx/kong-elastic-apm#3]
Hello,

I'm very interested in using your plugin, but the phrase in the README.md scares me 😆 

Any intentions of making this production ready?

**Comment by matthyx** [comment]
Hi @soer7022 I am working on a refactor to handle plugin server calls during the Log handler to not slow down packets when load increases. Once done it should scale much better.
I also have to document better how to test without a db.

**Comment by matthyx** [comment]
Please take a look now and let me know how that works for you.
