### ISSUE TITLE
climbing memory utilization by elastic-apm process

### ISSUE THREAD

**Issue by vnagireddy-symphonize** [matthyx/kong-elastic-apm#64]
There is a constant increase in the memory usage of the elastic-apm process based on the load on the gateway.  The expectation is for the usage to come down as the load decreases.  The plugin is being used with the release 3.5.0 of the Kong gateway.

**Comment by matthyx** [comment]
hi @vnagireddy-symphonize I have stopped development on this plugin since Kong have their own OTEL integration: https://docs.konghq.com/hub/kong-inc/opentelemetry/

I suggest you try using this one instead. Thanks!
